[versions]
junitEngineVersion = "5.10.1"
junitPlatformVersion = "1.10.1"
mockitoVersion = "5.7.0"
versionsVersion = "0.50.0"
nexusVersion = "1.3.0"
picocliVersion = "4.7.5"
parquetVersion = "1.13.1"
petitparserVersion = "2.3.1"
minimalJsonVersion = "0.10.0"
hadoopVersion = "3.3.6"
logbackVersion = "1.4.11"
assertjVersion = "3.24.2"
systemStubsVersion = "2.1.5"
downloadVersion = "5.5.0"
graalvmNativeImageVersion = "1.4.1"

[libraries]
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitEngineVersion" }
junitRunner = { group = "org.junit.platform", name = "junit-platform-runner", version.ref = "junitPlatformVersion" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoVersion" }
mockitoJunit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockitoVersion" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocliVersion" }
parquetCommon = { group = "org.apache.parquet", name = "parquet-common", version.ref = "parquetVersion" }
parquetColumn = { group = "org.apache.parquet", name = "parquet-column", version.ref = "parquetVersion" }
parquetHadoop = { group = "org.apache.parquet", name = "parquet-hadoop", version.ref = "parquetVersion" }
petitparser = { group = "com.github.petitparser", name = "petitparser-core", version.ref = "petitparserVersion" }
minimalJson = { group = "com.github.tonivade", name = "minimal-json", version.ref = "minimalJsonVersion" }
hadoopMapreduceClient = { group = "org.apache.hadoop", name = "hadoop-mapreduce-client-core", version.ref = "hadoopVersion" }
hadoopCommon = { group = "org.apache.hadoop", name = "hadoop-common", version.ref = "hadoopVersion" }
logbackClassic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logbackVersion" } 
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertjVersion" } 
systemStubs = { group = "uk.org.webcompere", name = "system-stubs-jupiter", version.ref = "systemStubsVersion" } 

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsVersion" }
graalvmNativeImage = { id = "org.mikeneck.graalvm-native-image", version.ref = "graalvmNativeImageVersion" }
download = {  id = "de.undercouch.download", version.ref = "downloadVersion" }
