name: Native Image
on:
  release:
    types: [published]

jobs:
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            uploaded_filename: pq-darwin-amd64
            local_path: build/native-image/pq
          - os: ubuntu-latest
            uploaded_filename: pq-linux-amd64
            local_path: build/native-image/pq
          - os: windows-latest
            uploaded_filename: pq-windows-amd64.exe
            local_path: build\native-image\pq.exe
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: 'gradle'

      # build
      - name: Native Image Linux
        run: ./gradlew nativeImage && ./gradlew compressExecutable
        shell: bash
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Native Image Macos
        run: ./gradlew nativeImage
        shell: bash
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Native Image Windows
        shell: cmd
        if: ${{ matrix.os == 'windows-latest' }}
        run: >-
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && gradlew.bat extractGraalvm && gradlew.bat nativeImage

      # test
      - name: Test Native Image Linux
        run: ./gradlew testNativeImage
        shell: bash
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Test Native Image Macos
        run: ./gradlew testNativeImage
        shell: bash
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Test Native Image Windows
        shell: cmd
        if: ${{ matrix.os == 'windows-latest' }}
        run: >-
          gradlew.bat testNativeImage

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
