name: Native Image
on:
  release:
    types: [published]

jobs:
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            uploaded_filename: pq-darwin-amd64
            local_path: build/native-image/pq
          - os: ubuntu-latest
            uploaded_filename: pq-linux-amd64
            local_path: build/native-image/pq
          - os: windows-latest
            uploaded_filename: pq-windows-amd64.exe
            local_path: build\native-image\pq.exe
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Native Image Linux
        run: ./gradlew nativeImage && ./gradlew compressExecutable
        shell: bash
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Native Image Macos
        run: ./gradlew nativeImage
        shell: bash
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Native Image Windows
        shell: cmd
        if: ${{ matrix.os == 'windows-latest' }}
        run: >-
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && gradlew.bat nativeImage
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
